apiVersion: v1
kind: Namespace
metadata:
  name: zomato-project
  labels:
    name: zomato-project
    project: zomato-clone
    environment: production
    team: devops
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    project: zomato-clone
    environment: production
    team: devops
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
    project: zomato-clone
    environment: production
    team: devops
---
apiVersion: v1
kind: Namespace
metadata:
  name: openkruise-system
  labels:
    name: openkruise-system
    project: zomato-clone
    environment: production
    team: devops
